-- MySQL Script generated by MySQL Workbench
-- Mon Oct 27 18:39:31 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alumnos` (
  `id_alumnos` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dni` INT(8) NOT NULL,
  `condicion` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_alumnos`),
  UNIQUE INDEX `id_alumno_UNIQUE` (`id_alumnos` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`materias` (
  `id_materias` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `condicion` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_materias`),
  UNIQUE INDEX `id_materias_UNIQUE` (`id_materias` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`anios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`anios` (
  `id_anios` INT NOT NULL,
  `descripcion` INT NOT NULL,
  PRIMARY KEY (`id_anios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estados` (
  `id_estados` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`notas` (
  `id_notas` INT NOT NULL,
  `id_alumnos` INT NOT NULL,
  `id_materias` INT NOT NULL,
  `nota_final` FLOAT NULL,
  `id_anios` INT NOT NULL,
  `id_estados` INT NOT NULL,
  `condicion` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_notas`, `id_alumnos`, `id_materias`),
  INDEX `fk_alumnos_has_materias_materias1_idx` (`id_materias` ASC) VISIBLE,
  INDEX `fk_alumnos_has_materias_alumnos1_idx` (`id_alumnos` ASC) VISIBLE,
  UNIQUE INDEX `id_alumnos_materias_UNIQUE` (`id_notas` ASC) VISIBLE,
  INDEX `fk_alumnos_materias_anios1_idx` (`id_anios` ASC) VISIBLE,
  INDEX `fk_alumnos_materias_estados1_idx` (`id_estados` ASC) VISIBLE,
  CONSTRAINT `fk_alumnos_has_materias_alumnos1`
    FOREIGN KEY (`id_alumnos`)
    REFERENCES `mydb`.`alumnos` (`id_alumnos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumnos_has_materias_materias1`
    FOREIGN KEY (`id_materias`)
    REFERENCES `mydb`.`materias` (`id_materias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumnos_materias_anios1`
    FOREIGN KEY (`id_anios`)
    REFERENCES `mydb`.`anios` (`id_anios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumnos_materias_estados1`
    FOREIGN KEY (`id_estados`)
    REFERENCES `mydb`.`estados` (`id_estados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
